services:
  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    network_mode: "host"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - redisdata:/data
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "3"

  minikeyvalue:
    build:
      context: ./minikeyvalue
      dockerfile: Dockerfile
    volumes:
      - /mnt/raid5/kvstore1:/tmp
    ports:
      - "3000-3005:3000-3005"
    network_mode: "host"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "3"

  connect:
    build: .
    image: connect-app
    restart: unless-stopped
    command: /bin/sh -c "./start_connect.sh"
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - ./frontend/dist:/usr/src/connect/frontend/dist:ro
      - ./assets:/usr/src/connect/assets
      - cargo-cache:/usr/local/cargo
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "10"

  useradmin:
    image: connect-app
    restart: unless-stopped
    command: /bin/sh -c "./start_useradmin.sh"
    depends_on:
      - connect
      - db
      - redis
      - minikeyvalue
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - ./assets:/usr/src/connect/assets
      - cargo-cache:/usr/local/cargo
      - /mnt/raid5/params:/params
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "10"

  nginx:
    image: nginx:alpine
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "3"

volumes:
  pgdata:
    external: true
    name: connect-killer_pgdata
  redisdata:
    external: true
    name: connect-killer_redisdata
  cargo-cache:
  connect-target:
